config/routes.rb
Rails.application.routes.draw do
  root 'rooms#new'

  resources :sessions, only: [:create]

  resources :rooms, only: [:new, :create] do
    get 'number', to: 'room_numbers#show', as: :number
  end
  get 'rooms/:number', to: 'rooms#show', as: :room
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/message.rb
# frozen_string_literal: true

class Message
  attr_reader :content, :created_at

  def initialize(content, sender)
    @content = content
    @sender = sender
    @created_at = Time.now
  end

  def sender_name
    @sender.name
  end
end

app/models/room.rb
class Room < ApplicationRecord
  after_initialize :generate_number, if: -> { number.blank? }

  validates :number, uniqueness: true

  private

  def generate_number
    self.number = 4.times.map { ('A'..'Z').to_a[rand(26)] }.join
  end
end

app/models/user.rb
class User < ApplicationRecord
  after_initialize :generate_name

  private

  def generate_name
    self.name = Time.now.to_i
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/concerns/current_user.rb
# frozen_string_literal: true

module CurrentUser
  private

  def set_current_user
    User.find(session[:user_id])
  rescue ActiveRecord::RecordNotFound
    session[:user_id] = User.create.id
  end
end

app/controllers/room_numbers_controller.rb
class RoomNumbersController < ApplicationController
  before_action :set_room

  def show
  end

  private

  def set_room
    @room = Room.find(params[:room_id])
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  include CurrentUser

  before_action :set_current_user, :check_number, only: [:show]

  def new; end

  def create
    room = Room.create
    flash[:alert] = 'Create room successfully! Please copy it.'
    redirect_to room_number_url(room)
  end

  def show
    @number = params[:number]
  end

  private

  def check_number
    room = Room.find_by(number: params[:number])
    if  room.blank?
      flash[:error] = 'Room number is not exists! Please input again.'
      redirect_to root_url if room.blank?
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    redirect_to room_path(params[:room_number]&.upcase)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def javascript_pack_tag_if_exists(filename, *options)
    file_path = "#{Webpacker.config.source_entry_path}/#{filename}.js"
    javascript_pack_tag(filename, *options) if File.exists?(file_path)
  end

  def page_class
    format('%s-%s-page', controller_name, action_name)
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/room_numbers_helper.rb
module RoomNumbersHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_flash_message.html.erb
<% if flash[:error] %>
  <div class="p-4 mb-4 text-sm text-red-700 bg-red-100 rounded-lg dark:bg-red-200 dark:text-red-800" role="alert">
    <span class="font-medium"><%= flash[:error] %></span>
  </div>
<% end %>
<% if flash[:alert] %>
  <div class="p-4 mb-4 text-sm text-green-700 bg-green-100 rounded-lg dark:bg-green-200 dark:text-green-800" role="alert">
    <span class="font-medium"><%= flash[:alert] %></span>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TalkOnline</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag "application", 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag_if_exists controller_name, 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <main class="page-container <%= page_class %> container max-w-xl mx-auto py-12 md:max-w-4xl">
      <%= render 'layouts/flash_message' %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/messages/_message.html.erb
<li>
  <div class="p-4 mb-4 max-w-prose text-sm text-blue-700 bg-blue-100 rounded-lg dark:bg-blue-200 dark:text-blue-800" role="alert">
    <p>
      <span class="font-bold"><%= message.sender_name %>:</span>
      <%= message.content %>
    </p>
    <p class="font-light text-xs text-gray-600">
      at <%= message.created_at.strftime('%F %T') %>
    </p>
  </div>
</li>

app/views/room_numbers/show.html.erb
<div class="flex items-center">
  <p><span class="font-bold">Room Number:</span><%= @room.number %></p>
  <%= link_to 'Join Room', room_path(@room.number), class: "ml-3 bg-teal-500 hover:bg-teal-700 border-teal-500 hover:border-teal-700 text-sm border-4 text-white py-1 px-2 rounded" %>
</div>

app/views/rooms/new.html.erb
<%= form_with url: sessions_path, class: 'w-full max-w-sm mx-auto' do |f| %>
  <div class="flex items-center border-b border-teal-500 py-2">
    <%= f.text_field :room_number, placeholder: 'Room Number', class: "appearance-none bg-transparent border-none w-full text-gray-700 mr-3 py-1 px-2 leading-tight focus:border-none focus:ring-0" %>
    <%= f.submit 'Join Room', class: "flex-shrink-0 bg-teal-500 hover:bg-teal-700 border-teal-500 hover:border-teal-700 text-sm border-4 text-white py-1 px-2 rounded" %>
  </div>
<% end %>
<%= form_with url: rooms_path, class: 'w-full max-w-sm mx-auto my-8' do |f| %>
  <p>
    Or you can
    <%= f.submit 'Create Room', class: 'text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800' %>
    and join it.
  </p>
<% end %>

app/views/rooms/show.html.erb
<input id="room-number" type="hidden" value="<%= @number %>"/>
<div class="py-8">
  <h1 class="text-4xl font-bold">Talk Online</h1>
  <p class="mt-2 text-lg text-gray-600">
    You can chat online here.
  </p>
</div>
<div class="grid grid-cols-4 gap-6">
  <div class="block col-span-full h-96">
    <ul class="message-container list-none
               overflow-y-auto overscroll-y-contain
               h-full block w-full
               px-3 py-2
               border rounded-md border-gray-300 shadow-sm"></ul>
  </div>
  <label class="block col-span-full">
    <textarea class="mt-1
                     block
                     w-full
                     rounded-md
                     border-gray-300
                     shadow-sm
                     focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50"
    rows="3"></textarea>
  </label>
  <button id="send-button" type="button" class="col-start-4 inline-block px-6 py-2.5 bg-blue-600 text-white font-medium text-xs leading-tight uppercase rounded-full shadow-md hover:bg-blue-700 hover:shadow-lg focus:bg-blue-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-blue-800 active:shadow-lg transition duration-150 ease-in-out">Send</button>
</div>

app/views/welcome/index.html.erb
<h1 class="text-3xl font-bold underline">
  Hello Talk Online
</h1>
<br/>
<p>
  This time is now: <%= Time.now %>
</p>